dist: trusty
language: python
python:
  - "3.6"
env:
  global:
  - REPO=self-repo-plugin
  - secure: DgacP/iPPmNuq2/SwQY2jFKWDMtJ6ivCR8j0e0EQSLvNxILglxlxFMn78KWWyD2fJVRdV/9M1JCj99hDSiQrmX2+y7imyyPqcj7IBB5d4AH115V7/kD2HyLRinXMwyDaNnT7VDmkByRSRebYZn63/WU3TF7vDMqkUT4ohSdLgz+bq1/evCmjgWfkWTwE/4feAzW9/9/fsoD1TBS4pNZeRQPgTLoS0Tr60VhoEUcFcTZe3Zhc+Y3sYNiWWRg+gxPz4x7lVYvRHogqfBIjp7LYB/QH0PLCSys+4vFCoUCJW6RdGu8eOwlgWB6vzhesKEhGXbnRGBrHwYa4IazBQ/c6Sb4UEm4ECvO2II8yPZwSJP2AzejHgqFLhRAfoR89a3jvXJNh+4jO4E742b/vyOPO3Tb1Nfl7y6flxrnqpCd3qlca8dFIzgnEBxQuLmW44I1wAI7bQY7YOSSS1gdSlEfyAPtOqqCVum5dAbgCn8BHn0isErLXPCOAK1vWW0DIvHrO1DMipt7rFB35oiYqetC0hY2iW3KYDQq5RoJn0r7dfZkFGWkzzqOPmx23YC75R0B7T/yUzZfHzBNzgTGEeWBa7JMb3IJ2g6IMuXPtf4qc8A8WCJYiy+sCDoYy+FbJYq6AjkHcM2KehVFzciiVKZS++fpFDU9QeZ/g2fz85nTHJng=

before_install:
  - sudo apt-get install -y xmlstarlet
install:
  # yes, I'm cloning the repo again. see https://stackoverflow.com/questions/32580821
  - cd ..
  - rm -rf self-repo-plugin
  - git clone https://github.com/opengisch/self-repo-plugin.git
  - cd self-repo-plugin
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/opengisch/self-repo-plugin.git
  - pip install -r requirements.txt
script:
  # TODO use pytest to run some tests
  - pwd
  - ls -l
env:
  global:
  - REPO=self-repo-plugin
  - secure: "DgacP/iPPmNuq2/SwQY2jFKWDMtJ6ivCR8j0e0EQSLvNxILglxlxFMn78KWWyD2fJVRdV/9M1JCj99hDSiQrmX2+y7imyyPqcj7IBB5d4AH115V7/kD2HyLRinXMwyDaNnT7VDmkByRSRebYZn63/WU3TF7vDMqkUT4ohSdLgz+bq1/evCmjgWfkWTwE/4feAzW9/9/fsoD1TBS4pNZeRQPgTLoS0Tr60VhoEUcFcTZe3Zhc+Y3sYNiWWRg+gxPz4x7lVYvRHogqfBIjp7LYB/QH0PLCSys+4vFCoUCJW6RdGu8eOwlgWB6vzhesKEhGXbnRGBrHwYa4IazBQ/c6Sb4UEm4ECvO2II8yPZwSJP2AzejHgqFLhRAfoR89a3jvXJNh+4jO4E742b/vyOPO3Tb1Nfl7y6flxrnqpCd3qlca8dFIzgnEBxQuLmW44I1wAI7bQY7YOSSS1gdSlEfyAPtOqqCVum5dAbgCn8BHn0isErLXPCOAK1vWW0DIvHrO1DMipt7rFB35oiYqetC0hY2iW3KYDQq5RoJn0r7dfZkFGWkzzqOPmx23YC75R0B7T/yUzZfHzBNzgTGEeWBa7JMb3IJ2g6IMuXPtf4qc8A8WCJYiy+sCDoYy+FbJYq6AjkHcM2KehVFzciiVKZS++fpFDU9QeZ/g2fz85nTHJng="
before_deploy:
  - git status
  #  - git checkout master

  # change the version number in metadata.txt file
  - sed -i "s/^\(version\s*=\s*\).*$/\1${TRAVIS_TAG}/" myplugin/metadata.txt
  - cat myplugin/metadata.txt

  # change the version number and the download url in plugins.xml
  - xmlstarlet ed -L -u //download_url -v "https://github.com/opengisch/self-repo-plugin/releases/download/${TRAVIS_TAG}/myplugin.zip" plugins.xml
  - xmlstarlet ed -L -u //pyqgis_plugin/@version -v "${TRAVIS_TAG}" plugins.xml
  - cat plugins.xml

  # commit metadata.txt and plugins.xml files
  - git add myplugin/metadata.txt plugins.xml
  - git commit -m "Update metadata.txt and plugins.xml to version ${TRAVIS_TAG}"
  - git push --set-upstream origin master

  # zip the plugin dir
  - zip -r myplugin.zip myplugin

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN} 
  file: myplugin.zip
  skip_cleanup: true
  on:
    repo: opengisch/self-repo-plugin
    tags: true
