dist: trusty
language: python
python:
  - "3.6"
env:
  global:
  - REPO=self-repo-plugin

before_install:
  - sudo apt-get install -y xmlstarlet

install: true

# TODO use pytest to run some tests
script: true

before_deploy:
  # yes, I'm cloning the repo again. see https://stackoverflow.com/questions/32580821
  - cd ..
  - rm -rf self-repo-plugin
  - git clone https://github.com/opengisch/self-repo-plugin.git
  - cd self-repo-plugin
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/opengisch/self-repo-plugin.git

  # zip the plugin dir
  - zip -r myplugin.zip myplugin

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: myplugin.zip
  skip_cleanup: true
  on:
    repo: opengisch/self-repo-plugin
    tags: true

after_deploy:
  # change the version number in metadata.txt file
  - sed -i "s/^\(version\s*=\s*\).*$/\1${TRAVIS_TAG}/" myplugin/metadata.txt
  - cat myplugin/metadata.txt

  # change the version number and the download url in plugins.xml
  - xmlstarlet ed -L -u //download_url -v "https://github.com/opengisch/self-repo-plugin/releases/download/${TRAVIS_TAG}/myplugin.zip" plugins.xml
  - xmlstarlet ed -L -u //pyqgis_plugin/@version -v "${TRAVIS_TAG}" plugins.xml
  - cat plugins.xml

  # commit metadata.txt and plugins.xml files
  - git add myplugin/metadata.txt plugins.xml
  - git commit -m "Update metadata.txt and plugins.xml to version ${TRAVIS_TAG}"
  - git push --set-upstream origin master

